services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./assistant:/app/assistant
      - ./writers_assistant:/app/writers_assistant
      - ./db.sqlite3:/app/db.sqlite3
    networks:
      - app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - './frontend:/app'
    networks:
      - app
    environment:
      - WATCHPACK_POLLING:true
      - CHOKIDAR_USEPOLLING:true