# Generated by Django 4.2.13 on 2024-05-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_paragraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='is_dialogue',
            field=models.BooleanField(default=False),
        ),
    ]
