# Generated by Django 4.2.13 on 2024-05-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_paragraph_is_dialogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
