# Generated by Django 4.2.13 on 2024-05-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
