# Generated by Django 4.2.13 on 2024-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_chapter_number_chapter_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
