# Generated by Django 4.2.13 on 2024-05-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_novel_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assistant.chapter'),
            preserve_default=False,
        ),
    ]
