# Generated by Django 4.2.13 on 2024-05-22 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_paragraph_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.chapter'),
        ),
    ]
