# Generated by Django 4.2.13 on 2024-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_scene_paragraph_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='genre',
            field=models.TextField(blank=True),
        ),
    ]
