# Generated by Django 4.2.13 on 2024-06-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0015_character_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='chapters',
            field=models.ManyToManyField(to='assistant.chapter'),
        ),
    ]
