# Generated by Django 4.2.13 on 2024-06-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_chapter_summary_character_chapters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='chapters',
        ),
        migrations.AddField(
            model_name='chapter',
            name='characters',
            field=models.ManyToManyField(to='assistant.character'),
        ),
    ]
